// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnnzi9nBE0WH9TCIgMI0SygCg-bbMQA4M',
    appId: '1:109719126441:web:6c174e5b8a72b878bbc4b8',
    messagingSenderId: '109719126441',
    projectId: 'venue-a6ce4',
    authDomain: 'venue-a6ce4.firebaseapp.com',
    storageBucket: 'venue-a6ce4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMacs-YXQ_Qh7AAz70e3BzkjteK0ZrjeU',
    appId: '1:109719126441:android:8246e1e491fe65d6bbc4b8',
    messagingSenderId: '109719126441',
    projectId: 'venue-a6ce4',
    storageBucket: 'venue-a6ce4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6uwq8YhRTfaORfvYOTOiKJY2C6p2eHb4',
    appId: '1:109719126441:ios:bc0c0e85e1a81febbbc4b8',
    messagingSenderId: '109719126441',
    projectId: 'venue-a6ce4',
    storageBucket: 'venue-a6ce4.appspot.com',
    iosBundleId: 'com.example.venue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6uwq8YhRTfaORfvYOTOiKJY2C6p2eHb4',
    appId: '1:109719126441:ios:5e860285e6326accbbc4b8',
    messagingSenderId: '109719126441',
    projectId: 'venue-a6ce4',
    storageBucket: 'venue-a6ce4.appspot.com',
    iosBundleId: 'com.example.venue.RunnerTests',
  );
}
